import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google"
import NavBar from "./components/nav/NavBar";
import Footer from "./components/footer/footer";
import HomeBanner from "./components/HomeBanner";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: "E-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex flex-col min-h-screen">
          <NavBar/>
          <main className="flex-grow text-cyan-500">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
